In [12]:
# task 1
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.unique(np.intersect1d(a,b))
c

array([2, 4])

In [19]:
# task 2
# apply arange(15) to generate an array from 0 to 14, then +1 for each element as to from 1 to 15
# apply np.reshape to shape
# apply np.T to T transpose the array.
array = (np.arange(15) + 1).reshape((3,5)).T
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [86]:
# task 3
a = np.array([12,5,7,15,3,1,8])
b = np.array([14,6,3,11,19,12,5])
# use np.in1d to compute a boolean array indicating whether each element of a is contained in b
c = np.in1d(a, b)
# use ~c to get the index in c opposed, then get d array with elements not included in b
d = a[~c]
d

[ True  True False False  True False False]


array([ 7, 15,  1,  8])

In [100]:
# task 4
# I record the numbers on each day's odometer from day 1 to day 35. Cause 4 days are out of work and the last day's odometer is
# known, which is the distance of two cities, 1548 miles.
# At first, I randomly create 28 ints ranging from 40 to 60, representing every day's riding miles.
odometer = []
a = 0
for x in np.random.randint(40,60,size = 28):
    a += x
    odometer.append(a)  # append 28 milage numbers into odometer
odometer = np.asarray(odometer) # transfer odometer from list to ndarray
odometer = np.insert(odometer, 28, 1548) # add the last day's odometer 1548 to the end of the array. Now 29 numbers.
# create an array including 2 numbers ranging from the current second biggest value to 1548. Then union the new array with odometer array.
# Now 31 numbers in odometer array.
odometer = np.union1d(odometer, np.random.randint(odometer[-2], 1548, size = 2)) 
b = np.random.randint(1,31, size = 4) # create a list consisting with 4 random integers from 1 to 30
odometer = np.insert(odometer, b, odometer[b]) # insert 4 same values of the indexs in the odometer array, that 4 random integers refer to.
# Now we have 35 numbers in odometer array.
odometer = np.insert(odometer, 0, 0) # In order to get the first day's riding distance in the subtranction.
# use numpy.ediff1d to get differences between two consecutive elements in the array.
milage = np.ediff1d(odometer)
milage
# use dict to show the result
milage_on_each_day = {'day'+str(i+1):milage[i] for i in range(35)}
milage_on_each_day

{'day1': 58,
 'day2': 40,
 'day3': 0,
 'day4': 53,
 'day5': 45,
 'day6': 47,
 'day7': 52,
 'day8': 0,
 'day9': 58,
 'day10': 53,
 'day11': 51,
 'day12': 49,
 'day13': 41,
 'day14': 59,
 'day15': 48,
 'day16': 54,
 'day17': 43,
 'day18': 56,
 'day19': 40,
 'day20': 46,
 'day21': 44,
 'day22': 42,
 'day23': 47,
 'day24': 56,
 'day25': 40,
 'day26': 59,
 'day27': 0,
 'day28': 57,
 'day29': 0,
 'day30': 57,
 'day31': 56,
 'day32': 56,
 'day33': 34,
 'day34': 87,
 'day35': 20}

In [102]:
# task 5
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\51759\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


numpy.ndarray

In [103]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

In [104]:
# the maximum yearly NYC consumption of water in millions of gallons per day
nyc_water.max(axis = 0)[2]

1512.0

In [118]:
# How many calendar years are represented within this data set?
print(len(nyc_water),'calendar years are represented.')

39 calendar years are represented.


In [136]:
# What is the mean and the standard deviation of the per capita daily water consumption?
mean = nyc_water.mean(axis = 0)[3]
std = nyc_water.std(axis = 0)[3]
print ("The mean is {}.".format(mean))
print ("The standard deviation is %s"%std)

The mean is 160.30769230769232.
The standard deviation is 31.51894330370624


In [108]:
# What is the increase or decrease in population from year to year?
pop_diff = np.diff(nyc_water, axis = 0)[:,1]
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])